### ISSUE TITLE
about image size

### ISSUE THREAD

**Issue by LooperzZ** [HJoonKwon/loftr-pytorch#3]
Does the size of the input image have to be an integer multiple of 64?

**Comment by HJoonKwon** [comment]
Input size matters only for resnet-fpn part since the latter part just uses what resnet toss them. If feature dimensions extracted by resnet is 1/8 and 1/2 of the original size then the input size should be an integer multiple of 8.

**Comment by LooperzZ** [comment]
How to adjust the code so that the input size is not an integer multiple of 8, thank you.



---- Replied Message ----
| From | Hyeokjoon ***@***.***> |
| Date | 02/15/2024 13:07 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [HJoonKwon/loftr-pytorch] about image size (Issue #3) |

Input size matters only for resnet-fpn part since the latter part just uses what resnet toss them. If feature dimensions extracted by resnet is 1/8 and 1/2 of the original size then the input size should be an integer multiple of 8.

**Comment by HJoonKwon** [comment]
I don't understand your question. Do you want the input size to not be multiple of 8?

**Comment by LooperzZ** [comment]
yes,like 300✖️300



---- Replied Message ----
| From | Hyeokjoon ***@***.***> |
| Date | 02/15/2024 14:31 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [HJoonKwon/loftr-pytorch] about image size (Issue #3) |

I don't understand your question. Do you want the input size to not be multiple of 8?

**Comment by HJoonKwon** [comment]
Is it what you want? or what you have? You can easily resize the image to be multiple of 8 and rescale the matching points later.

**Comment by LooperzZ** [comment]
When the scaled match points are reprojected back to the original image, there will be a certain error. I wondered if I could modify the network so that I didn't lose accuracy

**Comment by HJoonKwon** [comment]
Understood. In that case rather than using 1/8 and 1/2, you could use 1/10 and 1/2 or something similar. However, you should modify the CNN parameters like stride and padding to extract such feature maps. It will affect the whole process behind so the coarse-to-fine ratio should be adjusted as well. (4 to 5 in this example). Check all the shapes of output of each module using unit tests to make sure there are no bugs. It may work for 300x300, but there should be better solution that would work for general cases, which I think is open research question. 

P.S. Just an idea. How about padding instead of resizing to make input size a multiple of 8? You can mask out the padding part when matching.

**Comment by LooperzZ** [comment]
thank you.



---- Replied Message ----
| From | Hyeokjoon ***@***.***> |
| Date | 02/15/2024 15:53 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [HJoonKwon/loftr-pytorch] about image size (Issue #3) |

Understood. In that case rather than using 1/8 and 1/2, you could use 1/10 and 1/2 or something similar. However, you should modify the CNN parameters like stride and padding to extract such feature maps. It will affect the whole process behind so the coarse-to-fine ratio should be adjusted as well. (4 to 5 in this example). Check all the shapes of output of each module using unit tests to make sure there are no bugs.
